### ISSUE TITLE
Remove the obligatory 2 numbers for the minor versions

### ISSUE THREAD

**Issue by BVIAtol** [jasondcamp/pyway#41]
I'm trying to integrate pyway in an existing project that previously used Flyway.

The sql patchs of this project follows the pattern needed for pyway for the most part except for the minor version: they start at 1 (without a 0 in front) and may exeed 99.

I see [here](https://github.com/jasondcamp/pyway/blob/8af1c080cae12877d4d11248af1fb08eb0cc2d09/pyway/helpers.py#L38) that this minor version is strictly limited to 2 numbers.

Would it be possible to remove this limitation please?

**Comment by jasondcamp** [comment]
Tagged for version 0.3.22

**Comment by jasondcamp** [comment]
Upped to 0.3.23 - found a small bug on this one in 0.3.22, but it should be fixed in 0.3.23 and released.
