### ISSUE TITLE
Use environment variables in .pyway.conf file

### ISSUE THREAD

**Issue by juliennowak** [jasondcamp/pyway#43]
Hello, 

Is it possible to use environment variables in the .pyway.conf file. I want to do something like: 

```
database_type: postgres
database_username: ${DB_USER}
database_password: ${DB_PASSWORD}
database_host: ${DB_HOST}
database_port: ${DB_PORT}
database_name: ${DB_DBNAME}
database_migration_dir: infra/pyway
database_table: public.pyway
```

I get the following error : _invalid integer value "${ELI_DB_PORT}" for connection option "port"_
Is it something supported with another syntax or not supported at all? 

Thanks
Julien

**Comment by jasondcamp** [comment]
This isnt supported now, but a good feature enhancement. I'll add it to the list of work for the next version.

**Comment by jasondcamp** [comment]
Tagged for version 0.3.22

**Comment by jasondcamp** [comment]
Update for 0.3.23 and released
