### ISSUE TITLE
Add tests for postgres

### ISSUE THREAD

**Issue by jasondcamp** [jasondcamp/pyway#44]
We missed an issue with SQL in the postgres factory, because we're not testing against postgres. Work on this.

**Comment by walnutist** [comment]
I can see by default the Config obj is instantiated with assumed postgres connection info, if there is no env_vars, no conf, whatsoever. This is not expected behavior for user, the proper way might be to raise empty value error, or even better, a validation error message.

**Comment by jasondcamp** [comment]
Added postgres integration tests, will look into the suggestion above for default config behavior

**Comment by jasondcamp** [comment]
Cleaned up the ConfigFile defaults in 0.3.25
