### ISSUE TITLE
Use `cursor.executescript` for sqlite

### ISSUE THREAD

**Issue by jmpicnic** [jasondcamp/pyway#68]
When executing a migration with a file that contains more than one sql statement against `sqlite`, it gives an exception:

```
sqlite3.ProgrammingError: You can only execute one statement at a time.
```

Looking at the code, it seems that [sqlite.py](https://github.com/jasondcamp/pyway/blob/main/pyway/dbms/sqlite.py) in [line 40](https://github.com/jasondcamp/pyway/blob/8b9b14c7115a7dab27afbcd2c8172e2c880f8c49/pyway/dbms/sqlite.py#L37C5-L44C20) is calling `cursor.execute(script)`.

To support files with multiple statements with `sqlite` the call should be `cursor.executescript(script)`

Created fork and pull request with the change in case it helps. [See the PR here](https://github.com/jasondcamp/pyway/pull/69)

**Comment by jmpicnic** [comment]
@jasondcamp I am not sure you saw this issue yet with the PR I created to try to help. Please let me know if there are other questions or issues with the PR.

Thanks

Miguel

**Comment by jasondcamp** [comment]
Thank you for this PR! Merged and I'll cut a new release today.

**Comment by jmpicnic** [comment]
Awesome, thanks a lot!

Miguel

-----------
Miguel Pinilla
www.linkedin.com/in/mpinilla/
+1-650.489.0329

See my book at Amazon: https://amazon.com/author/miguel.pinilla
